inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    - 'bin/**/*'
    - 'db/schema.rb'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

Metrics/LineLength:
  Max: 100

Metrics/MethodLength:
  Exclude:
    - 'db/migrate/*'

Style/ClassAndModuleChildren:
  Exclude:
    - 'app/controllers/**/*'
    - 'app/helpers/api/*'
