AllCops:
  Exclude:
    - 'bin/**/*'
    - 'db/schema.rb'

Rails:
  Enabled: true

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

Metrics/LineLength:
  Max: 100
  Exclude:
    - 'config/**/*'

Metrics/MethodLength:
  Exclude:
    - 'db/migrate/*'

Rails/DynamicFindBy:
  Whitelist:
    - 'find_by_credentials'

Style/ClassAndModuleChildren:
  Exclude:
    - 'app/controllers/**/*'
    - 'app/helpers/api/*'

Style/Documentation:
  Exclude:
    - 'app/controllers/**/*'
    - 'app/helpers/api/*'
    - 'app/helpers/application_helper.rb'
    - 'app/helpers/static_pages_helper.rb'
    - 'app/mailers/application_mailer.rb'
    - 'config/**/*'
    - 'db/migrate/*'
